Changing the way we build Trilinos so that "make" simply builds the libraries. Tests and examples will be built with "make tests" and "make examples", respectively.  I will send a note with more details to the developer list after I am done making these changes.

diff --git a/packages/rbgen/configure b/packages/rbgen/configure
--- a/packages/rbgen/configure
+++ b/packages/rbgen/configure
@@ -744,6 +744,10 @@ BUILD_TESTS_TRUE
 BUILD_TESTS_FALSE
 BUILD_EXAMPLES_TRUE
 BUILD_EXAMPLES_FALSE
+SUB_TEST_TRUE
+SUB_TEST_FALSE
+SUB_EXAMPLE_TRUE
+SUB_EXAMPLE_FALSE
 BUILD_RBGEN_EPETRA_TRUE
 BUILD_RBGEN_EPETRA_FALSE
 BUILD_RBGEN_EPETRAEXT_TRUE
@@ -1366,17 +1370,16 @@ Optional Features:
   --enable-dependency-tracking   do not reject slow dependency extractors
   --enable-rbgen-drivers  Build RBGen drivers (binaries) (default is yes)
   --enable-rbgen-netcdf   Enable NetCDF support (default is no)
-  --enable-tests          Build tests for all Trilinos packages (not all
-                          packages are sensitive to this option) (default is
-                          yes)
+  --enable-tests          Make tests for all Trilinos packages buildable with
+                          'make tests' (default is yes)
 
-  --enable-rbgen-tests    Build RBGen tests (default is yes if --disable-tests
-                          is not specified)
-  --enable-examples       Build examples for all Trilinos packages (not all
-                          packages are sensitive to this option) (default is
-                          yes)
-  --enable-rbgen-examples Build RBGen examples (default is yes if
-                          --disable-examples is not specified)
+  --enable-rbgen-tests    Make RBGen tests buildable with 'make tests'
+                          (default is yes if --disable-tests is not specified)
+  --enable-examples       Make examples for all Trilinos packages buildable
+                          with 'make examples' (default is yes)
+  --enable-rbgen-examples Make RBGen examples buildable with 'make examples'
+                          (default is yes if --disable-examples is not
+                          specified)
   --enable-libcheck       Check for some third-party libraries including BLAS
                           and LAPACK. (Cannot be disabled unless tests and
                           examples are also disabled.) (default is yes)
@@ -7712,10 +7715,6 @@ fi
 # Checks if tests and examples should be built
 # ------------------------------------------------------------------------
 
-#  #np# - These options can disable the tests and examples of a package.
-#  #np# - Packages that do not have tests or examples should #-out the
-#  #np# - option(s) that does (do) not apply.
-
 
 # Check whether --enable-tests was given.
 if test "${enable_tests+set}" = set; then
@@ -7847,6 +7846,28 @@ fi
 else
   BUILD_EXAMPLES_TRUE='#'
   BUILD_EXAMPLES_FALSE=
+fi
+
+
+#We now build tests and examples through separate make targets, rather than
+#during "make".  We still need to conditionally include the test and example
+#in SUBDIRS, even though SUB_TEST and SUB_EXAMPLE will never be
+#defined, so that the tests and examples are included in the distribution
+#tarball.
+ if test "X$ac_cv_use_sub_test" = "Xyes"; then
+  SUB_TEST_TRUE=
+  SUB_TEST_FALSE='#'
+else
+  SUB_TEST_TRUE='#'
+  SUB_TEST_FALSE=
+fi
+
+ if test "X$ac_cv_use_sub_example" = "Xyes"; then
+  SUB_EXAMPLE_TRUE=
+  SUB_EXAMPLE_FALSE='#'
+else
+  SUB_EXAMPLE_TRUE='#'
+  SUB_EXAMPLE_FALSE=
 fi
 
 
@@ -11595,6 +11616,20 @@ echo "$as_me: error: conditional \"BUILD_EXAMPLES\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${SUB_TEST_TRUE}" && test -z "${SUB_TEST_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SUB_TEST\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SUB_TEST\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${SUB_EXAMPLE_TRUE}" && test -z "${SUB_EXAMPLE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SUB_EXAMPLE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SUB_EXAMPLE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${BUILD_RBGEN_EPETRA_TRUE}" && test -z "${BUILD_RBGEN_EPETRA_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"BUILD_RBGEN_EPETRA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -12326,6 +12361,10 @@ BUILD_TESTS_TRUE!$BUILD_TESTS_TRUE$ac_delim
 BUILD_TESTS_FALSE!$BUILD_TESTS_FALSE$ac_delim
 BUILD_EXAMPLES_TRUE!$BUILD_EXAMPLES_TRUE$ac_delim
 BUILD_EXAMPLES_FALSE!$BUILD_EXAMPLES_FALSE$ac_delim
+SUB_TEST_TRUE!$SUB_TEST_TRUE$ac_delim
+SUB_TEST_FALSE!$SUB_TEST_FALSE$ac_delim
+SUB_EXAMPLE_TRUE!$SUB_EXAMPLE_TRUE$ac_delim
+SUB_EXAMPLE_FALSE!$SUB_EXAMPLE_FALSE$ac_delim
 BUILD_RBGEN_EPETRA_TRUE!$BUILD_RBGEN_EPETRA_TRUE$ac_delim
 BUILD_RBGEN_EPETRA_FALSE!$BUILD_RBGEN_EPETRA_FALSE$ac_delim
 BUILD_RBGEN_EPETRAEXT_TRUE!$BUILD_RBGEN_EPETRAEXT_TRUE$ac_delim
@@ -12340,7 +12379,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 44; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 48; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
